# Generated by Django 3.1.4 on 2021-01-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_animal', models.CharField(max_length=30)),
                ('sexe_animal', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medecin', models.CharField(max_length=30)),
                ('prenom_medecin', models.CharField(max_length=30)),
                ('contact_medecin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parent', models.CharField(max_length=30)),
                ('prenom_parent', models.CharField(max_length=45)),
                ('tel_parent', models.CharField(max_length=15)),
                ('email_parent', models.EmailField(max_length=30)),
                ('adresse_parent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type_animal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendezvous', models.DateField()),
                ('heure_rendezvous', models.TimeField(default=None)),
                ('animal_rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
                ('medecin_rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='parent_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.parent'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.typeanimal'),
        ),
    ]
